name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61803d61d931c2cf4fef98c205fdae943aad74960a0783a4b9844e6523e9ffc1"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
