name = "FabricSMP"
author = "Fabric Community"
version = "3.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2eedf43b623819a85b95e4572773558e3e7b5000025e4f142ab8721d21bf4fb"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
