name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5075bd468f57c894b1414ded892ef4b765a701bd5631663fe7cd6ba411e5c570"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
