name = "FabricSMP"
author = "Fabric Community"
version = "3.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2871353873f7783742b4b6a72db47b3c04a37df4793f4c1f3eeee741741de602"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
