name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10a14183b0b3136de5166ccf8ce0036d83aa1e685f22b03b4d66522fe904270e"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
