name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4ffe2dce37eb1f001f5ff3f0bc408a917419819ba1455d9dec314c8a29f785b"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
