name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cbcbc140ef2e087934afebd422b7909cba99e04cde54538958c930d35a85c3f"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
