name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d6a5f663f6a8be03750abad24b18a13c7aed954752edcf80d68d42a21ccee0a"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
