name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afebac6403b3319d3577d2babad08a5118cb138d56c09444bc03db9d76c9cc21"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
