name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f9aa24b6632989c1d55b0c090a4e23f8105f38ff2d8db15af9a57a4578a977f"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
