name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0dab38419f65c2d54d172e737fcc4b77002e678f7f05346e950c217ad2baabe"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "35.1.10"
jumploader-version-id = 3103389
project-id = 0
