name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3ea9a8a5a4a56286e24a35483a5f750604ad81118ab038dcc1ed5bfb8c9299c"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
