name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7076cd878a15ee9b73d9a211c6c2d14aa34725d3be81ad2e3f4171ffb17b8f00"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
