name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6beca87e57394317160f1fbabd4406ab1c7cb88a0f2edbf36c465518b67c59d0"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
