name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e116495eed9e85d41eeaf6678cd4d8c6a6d09b2199e4f4a53696513835dbc1"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
