name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d87ad37e2b90a4697931eeb6b7a328bf20628985cac4d546d27d2b795ae6eb5"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
