name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b155b5d8e6bc52c06d4e78ed5f6297ee36b34f45ddab81717c56e3ff0375043"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
