name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5111e332147874dcae64d0cb0b0220d33ffe8274d2bb060eedd78a8efd45829d"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
