name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf73444fd3cc77c69fd12208eec834d14ba72ca1b78499dab08c857f4ae83889"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
