name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06ef9f0c84cdcc42f54f8dfb9648dc1104afd14f45e0d230204ed76368bc792b"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
