name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "583fab8630056b905e4ce887d32bd2da78236da56fa64d10dd1d181257dc66e8"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
