name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68ace38384110fddeb5005ff8a7b7ffc741da6a3d50995d5d9e051508d8a3ae9"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
