name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "269b93742722f7ebfd771b13d8112367c8fbaf399b8bcadeb2ac8fe111b828cd"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
