name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f310e6f8a1a352516ca4eeb58da6b8b46cc1c8ed9c19e35413b24bdd6f8545d2"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
