name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21ce27a1c9b8ef2c8d02b574ab71c7c130db8a6c9ea77bd9a947de5e64c2abc6"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
