name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0404185d6ed5ad405f4fe7935ea4fcf9fa1c9d22d37f9435c133efc278218488"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
