name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea22cbccc2b3e7179f85e657e0975589ab4ad890611f02b05d373853e2db429a"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
