name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34f514e3589bd25069d04ef47413f9b2ebe500d7a929b3b5a9d9acfc77378a4d"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
