name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "756ea8b9ef1fdb8dca5214ef38ff074302eaa40acdc98a93b193844adce47fc6"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
