name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edfd9a0898c79eddc6c5aab1141c1960d28743a4ce34573cf5c4ee52ffcfd7c8"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
