name = "FabricSMP"
author = ""
version = ""

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b66cac8e1ff5cad1b5cbc67d8f6f381d79ff0d667ad64e02a9ddccd9c3d6e952"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
