name = "FSMP"
author = "Fabric"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d0ce352352c8629a83698ac78cc8749e571e5bc402cf9f2998d4bf58fbcd4ef"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
