name = "Antique Atlas"
filename = "antiqueatlas-5.4.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3171/98/antiqueatlas-5.4.2-fabric.jar"
hash-format = "murmur2"
hash = "986508209"

[update]
[update.curseforge]
file-id = 3171098
project-id = 227795
release-channel = "beta"
