name = "Architectury API (Fabric)"
filename = "architectury-1.5.105-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3188/529/architectury-1.5.105-fabric.jar"
hash-format = "murmur2"
hash = "3904829834"

[update]
[update.curseforge]
file-id = 3188529
project-id = 419697
release-channel = "beta"
