name = "Architectury API (Fabric)"
filename = "architectury-1.5.108-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3194/695/architectury-1.5.108-fabric.jar"
hash-format = "murmur2"
hash = "2609492093"

[update]
[update.curseforge]
file-id = 3194695
project-id = 419697
release-channel = "beta"
