name = "All The Blocks You Want"
filename = "atbyw-1.16.4-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3147/873/atbyw-1.16.4-1.3.4.jar"
hash-format = "murmur2"
hash = "1163291214"

[update]
[update.curseforge]
file-id = 3147873
project-id = 428415
release-channel = "beta"
