name = "BetterNether"
filename = "better-nether-5.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3133/763/better-nether-5.0.4.jar"
hash-format = "murmur2"
hash = "996456162"

[update]
[update.curseforge]
file-id = 3133763
project-id = 311377
release-channel = "beta"
