name = "BetterEnd"
filename = "better-end-0.8.5-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3154/524/better-end-0.8.5-beta.jar"
hash-format = "murmur2"
hash = "3774227232"

[update]
[update.curseforge]
file-id = 3154524
project-id = 413596
release-channel = "beta"
