name = "BetterEnd"
filename = "better-end-0.8.3-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3147/42/better-end-0.8.3-beta.jar"
hash-format = "murmur2"
hash = "1582522902"

[update]
[update.curseforge]
file-id = 3147042
project-id = 413596
release-channel = "beta"
