name = "BetterEnd"
filename = "better-end-0.8.7-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3166/133/better-end-0.8.7-beta.jar"
hash-format = "murmur2"
hash = "3359370265"

[update]
[update.curseforge]
file-id = 3166133
project-id = 413596
release-channel = "beta"
