name = "BetterEnd"
filename = "better-end-0.8.0-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3138/832/better-end-0.8.0-beta.jar"
hash-format = "murmur2"
hash = "2940790883"

[update]
[update.curseforge]
file-id = 3138832
project-id = 413596
release-channel = "beta"
