name = "Better Enchanted Books (Fabric)"
filename = "better-enchanted-books-1.16.3-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/480/better-enchanted-books-1.16.3-1.1.4.jar"
hash-format = "murmur2"
hash = "1824861525"

[update]
[update.curseforge]
file-id = 3068480
project-id = 369122
release-channel = "beta"
