name = "Blockus"
filename = "blockus-2.0.0+1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3138/610/blockus-2.0.0+1.16.4.jar"
hash-format = "murmur2"
hash = "523393501"

[update]
[update.curseforge]
file-id = 3138610
project-id = 312289
release-channel = "beta"
