name = "Brute Imitation"
filename = "bruteimitation-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2997/33/bruteimitation-1.0.0.jar"
hash-format = "murmur2"
hash = "2554851221"

[update]
[update.curseforge]
file-id = 2997033
project-id = 393799
release-channel = "beta"
