name = "Campanion"
filename = "campanion-1.2.0+build.39.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3043/61/campanion-1.2.0+build.39.jar"
hash-format = "murmur2"
hash = "3935849340"

[update]
[update.curseforge]
file-id = 3043061
project-id = 373138
release-channel = "beta"
