name = "Campanion"
filename = "campanion-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3179/423/campanion-1.3.2.jar"
hash-format = "murmur2"
hash = "2383229938"

[update]
[update.curseforge]
file-id = 3179423
project-id = 373138
release-channel = "beta"
