name = "Campanion"
filename = "campanion-1.3.0+build.49.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3135/325/campanion-1.3.0+build.49.jar"
hash-format = "murmur2"
hash = "52613545"

[update]
[update.curseforge]
file-id = 3135325
project-id = 373138
release-channel = "beta"
