name = "Campanion"
filename = "campanion-1.3.1+build.51.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3139/44/campanion-1.3.1+build.51.jar"
hash-format = "murmur2"
hash = "1505287037"

[update]
[update.curseforge]
file-id = 3139044
project-id = 373138
release-channel = "beta"
