name = "Campanion"
filename = "campanion-1.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3189/338/campanion-1.3.3.jar"
hash-format = "murmur2"
hash = "1076127616"

[update]
[update.curseforge]
file-id = 3189338
project-id = 373138
release-channel = "beta"
