name = "Cardinal Components"
filename = "Cardinal-Components-API-2.7.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3121/927/Cardinal-Components-API-2.7.9.jar"
hash-format = "murmur2"
hash = "2857506655"

[update]
[update.curseforge]
file-id = 3121927
project-id = 318449
release-channel = "beta"
