name = "Cardinal Components"
filename = "Cardinal-Components-API-2.7.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3145/473/Cardinal-Components-API-2.7.10.jar"
hash-format = "murmur2"
hash = "4195793848"

[update]
[update.curseforge]
file-id = 3145473
project-id = 318449
release-channel = "beta"
