name = "Carpet"
filename = "fabric-carpet-1.16.5-1.4.23+v210115.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3169/450/fabric-carpet-1.16.5-1.4.23+v210115.jar"
hash-format = "murmur2"
hash = "2460422855"

[update]
[update.curseforge]
file-id = 3169450
project-id = 349239
release-channel = "beta"
