name = "Craftable Horse Armour & Saddle [CHA&S]"
filename = "CraftableHorseArmour-1.16.X-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3116/758/CraftableHorseArmour-1.16.X-1.4.0.jar"
hash-format = "murmur2"
hash = "790438350"

[update]
[update.curseforge]
file-id = 3116758
project-id = 224841
release-channel = "beta"
