name = "Christmas Spirit: Rewoven"
filename = "cspirit-1.0.0+mc.1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3145/91/cspirit-1.0.0+mc.1.16.4.jar"
hash-format = "murmur2"
hash = "4130007312"

[update]
[update.curseforge]
file-id = 3145091
project-id = 429980
release-channel = "beta"
