name = "Crumbs (Fabric)"
filename = "crumbs-1.0.6+1.16.4-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3145/676/crumbs-1.0.6+1.16.4-fabric.jar"
hash-format = "murmur2"
hash = "4213418455"

[update]
[update.curseforge]
file-id = 3145676
project-id = 412205
release-channel = "beta"
