name = "CSS Potted Plant"
filename = "css-potted-plant-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3140/967/css-potted-plant-1.0.1.jar"
hash-format = "murmur2"
hash = "1571577596"

[update]
[update.curseforge]
file-id = 3140967
project-id = 428690
release-channel = "beta"
