name = "Discerning Furnace"
filename = "discerning-furnace-1.0.0+MC1.16.1-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3141/51/discerning-furnace-1.0.0+MC1.16.1-1.16.4.jar"
hash-format = "murmur2"
hash = "996526486"

[update]
[update.curseforge]
file-id = 3141051
project-id = 428966
release-channel = "beta"
