name = "Draylar's Battle Towers"
filename = "battletowers-3.3.1-beta-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3135/757/battletowers-3.3.1-beta-1.16.4.jar"
hash-format = "murmur2"
hash = "3792067351"

[update]
[update.curseforge]
file-id = 3135757
project-id = 315386
release-channel = "beta"
