name = "Eldritch Mobs"
filename = "eldritch-mobs-1.5.3.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3131/878/eldritch-mobs-1.5.3.jar"
hash-format = "murmur2"
hash = "162488904"

[update]
[update.curseforge]
file-id = 3131878
project-id = 392015
release-channel = "beta"
