name = "Eldritch Mobs"
filename = "eldritch-mobs-1.6.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3181/347/eldritch-mobs-1.6.6.jar"
hash-format = "murmur2"
hash = "441288075"

[update]
[update.curseforge]
file-id = 3181347
project-id = 392015
release-channel = "beta"
