name = "Eldritch Mobs"
filename = "eldritch-mobs-1.6.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3170/49/eldritch-mobs-1.6.2.jar"
hash-format = "murmur2"
hash = "1254151009"

[update]
[update.curseforge]
file-id = 3170049
project-id = 392015
release-channel = "beta"
