name = "Eldritch Mobs"
filename = "eldritch-mobs-1.6.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3172/17/eldritch-mobs-1.6.5.jar"
hash-format = "murmur2"
hash = "2945251974"

[update]
[update.curseforge]
file-id = 3172017
project-id = 392015
release-channel = "beta"
