name = "Emotecraft (Fabric)"
filename = "emotecraft-for-MC1.16.4-1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3122/838/emotecraft-for-MC1.16.4-1.2.3.jar"
hash-format = "murmur2"
hash = "3190919602"

[update]
[update.curseforge]
file-id = 3122838
project-id = 397809
release-channel = "beta"
