name = "Emotecraft (Fabric)"
filename = "emotecraft-for-MC1.16.5-1.3snapshot3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3190/563/emotecraft-for-MC1.16.5-1.3snapshot3.jar"
hash-format = "murmur2"
hash = "4068787032"

[update]
[update.curseforge]
file-id = 3190563
project-id = 397809
release-channel = "beta"
