name = "ExperimentAway"
filename = "experimentaway-1.0.2.jar"
side = "both"

[download]
url = "https://github.com/user11681/ExperimentAway/releases/download/1.0.2/experimentaway-1.0.2.jar"
hash-format = "sha256"
hash = "98fac7f98be33202ec38f8e481e0e4bbe709df624222e359409de6765bba4722"