name = "FabriKommander"
filename = "FabriKommander-1.0.0-MC1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3098/760/FabriKommander-1.0.0-MC1.16.3.jar"
hash-format = "murmur2"
hash = "229684231"

[update]
[update.curseforge]
file-id = 3098760
project-id = 416117
release-channel = "beta"
