name = "Nether Roof Nerf [Fabric]"
filename = "netherroof-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3074/491/netherroof-1.0.0.jar"
hash-format = "murmur2"
hash = "978280025"

[update]
[update.curseforge]
file-id = 3074491
project-id = 362027
release-channel = "beta"
