name = "Flamingo, oh, oh, oh..."
filename = "Flamingo-oh-oh-oh-1.0.3-MC1.16.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3098/192/Flamingo-oh-oh-oh-1.0.3-MC1.16.3-fabric.jar"
hash-format = "murmur2"
hash = "2609151667"

[update]
[update.curseforge]
file-id = 3098192
project-id = 396461
release-channel = "beta"
