name = "Frying Pan"
filename = "fryingpan-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3138/971/fryingpan-1.0.2.jar"
hash-format = "murmur2"
hash = "984433353"

[update]
[update.curseforge]
file-id = 3138971
project-id = 413166
release-channel = "beta"
