name = "Gentle Fawn"
filename = "GentleFawn-1.1.2-MC1.16.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3116/774/GentleFawn-1.1.2-MC1.16.3-fabric.jar"
hash-format = "murmur2"
hash = "1571276362"

[update]
[update.curseforge]
file-id = 3116774
project-id = 395656
release-channel = "beta"
