name = "Gentle Picking"
filename = "gentle-picking-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3133/806/gentle-picking-1.0.2.jar"
hash-format = "murmur2"
hash = "700229456"

[update]
[update.curseforge]
file-id = 3133806
project-id = 422476
release-channel = "beta"
