name = "Gravestones"
filename = "gravestones-v1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3135/731/gravestones-v1.7.jar"
hash-format = "murmur2"
hash = "773664770"

[update]
[update.curseforge]
file-id = 3135731
project-id = 373595
release-channel = "beta"
