name = "Guillotine"
filename = "guillotine-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3179/696/guillotine-1.0.0.jar"
hash-format = "murmur2"
hash = "3288869173"

[update]
[update.curseforge]
file-id = 3179696
project-id = 439627
release-channel = "beta"
