name = "Gunpowder"
filename = "gunpowder-base-0.3.5+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3173/443/gunpowder-base-0.3.5+1.16.5.jar"
hash-format = "murmur2"
hash = "1886587716"

[update]
[update.curseforge]
file-id = 3173443
project-id = 350123
release-channel = "beta"
