name = "Hypnos"
filename = "hypnos-0.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3082/894/hypnos-0.1.1.jar"
hash-format = "murmur2"
hash = "2160293215"

[update]
[update.curseforge]
file-id = 3082894
project-id = 413160
release-channel = "beta"
