name = "Lil Tater Reloaded"
filename = "LilTaterReloaded-1.1.10+1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3086/860/LilTaterReloaded-1.1.10+1.16.3.jar"
hash-format = "murmur2"
hash = "3563777677"

[update]
[update.curseforge]
file-id = 3086860
project-id = 383066
release-channel = "beta"
