name = "Linkart: Fabric"
filename = "linkart-1.3.3+fabric-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3085/894/linkart-1.3.3+fabric-1.16.3.jar"
hash-format = "murmur2"
hash = "2459936070"

[update]
[update.curseforge]
file-id = 3085894
project-id = 382627
release-channel = "beta"
