name = "Lootstrap"
filename = "lootstrap-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3095/294/lootstrap-1.1.0.jar"
hash-format = "murmur2"
hash = "2424849933"

[update]
[update.curseforge]
file-id = 3095294
project-id = 361134
release-channel = "beta"
