name = "microDurability"
filename = "microDurability-0.3.0+1.16.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3136/865/microDurability-0.3.0+1.16.3.jar"
hash-format = "murmur2"
hash = "2580196803"

[update]
[update.curseforge]
file-id = 3136865
project-id = 409222
release-channel = "beta"
