name = "Mo' Structures"
filename = "mostructures-1.0.0+mc.1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3123/101/mostructures-1.0.0+mc.1.16.4.jar"
hash-format = "murmur2"
hash = "2347649058"

[update]
[update.curseforge]
file-id = 3123101
project-id = 378266
release-channel = "beta"
