name = "Mod Menu"
filename = "modmenu-1.16.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3194/84/modmenu-1.16.6.jar"
hash-format = "murmur2"
hash = "2917434636"

[update]
[update.curseforge]
file-id = 3194084
project-id = 308702
release-channel = "beta"
