name = "Mooblooms"
filename = "mooblooms-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3155/167/mooblooms-1.4.0.jar"
hash-format = "murmur2"
hash = "3432799420"

[update]
[update.curseforge]
file-id = 3155167
project-id = 333946
release-channel = "beta"
