name = "Nbt Crafting (Fabric)"
filename = "nbtcrafting-2.0.3+mc1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3145/245/nbtcrafting-2.0.3+mc1.16.4.jar"
hash-format = "murmur2"
hash = "3750173357"

[update]
[update.curseforge]
file-id = 3145245
project-id = 314633
release-channel = "beta"
