name = "Netherite Plus"
filename = "netherite-plus-mod-1.3.3-1.16.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3172/59/netherite-plus-mod-1.3.3-1.16.5-fabric.jar"
hash-format = "murmur2"
hash = "3814716591"

[update]
[update.curseforge]
file-id = 3172059
project-id = 394120
release-channel = "beta"
