name = "Netherite Plus Mod"
filename = "netherite-plus-mod-1.3.12-1.16.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3186/378/netherite-plus-mod-1.3.12-1.16.5-fabric.jar"
hash-format = "murmur2"
hash = "3798731505"

[update]
[update.curseforge]
file-id = 3186378
project-id = 394120
release-channel = "beta"
