name = "Netherite Plus Mod"
filename = "netherite-plus-mod-1.3.15-1.16.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3195/85/netherite-plus-mod-1.3.15-1.16.5-fabric.jar"
hash-format = "murmur2"
hash = "49304801"

[update]
[update.curseforge]
file-id = 3195085
project-id = 394120
release-channel = "beta"
