name = "Refabricated Slabs"
filename = "slabref-0.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3143/850/slabref-0.1.1.jar"
hash-format = "murmur2"
hash = "2295431528"

[update]
[update.curseforge]
file-id = 3143850
project-id = 429651
release-channel = "beta"
