name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures-1.16.4-1.7.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3169/629/repurposed_structures-1.16.4-1.7.4.jar"
hash-format = "murmur2"
hash = "573426169"

[update]
[update.curseforge]
file-id = 3169629
project-id = 391366
release-channel = "beta"
