name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-5.9.171.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3195/536/RoughlyEnoughItems-5.9.171.jar"
hash-format = "murmur2"
hash = "1564925655"

[update]
[update.curseforge]
file-id = 3195536
project-id = 310111
release-channel = "beta"
