name = "Skin Swapper"
filename = "Skin Swapper 1.16.4.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3125/839/Skin Swapper 1.16.4.jar"
hash-format = "murmur2"
hash = "1051725760"

[update]
[update.curseforge]
file-id = 3125839
project-id = 358486
release-channel = "beta"
