name = "Smithee"
filename = "wraith-smithee-0.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3152/939/wraith-smithee-0.1.4.jar"
hash-format = "murmur2"
hash = "2709225618"

[update]
[update.curseforge]
file-id = 3152939
project-id = 430733
release-channel = "beta"
