name = "Supernatural Crops"
filename = "supernatural-crops-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3147/636/supernatural-crops-1.0.2.jar"
hash-format = "murmur2"
hash = "2284633639"

[update]
[update.curseforge]
file-id = 3147636
project-id = 430458
release-channel = "beta"
