name = "Supernatural Crops"
filename = "supernatural-crops-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3152/631/supernatural-crops-1.0.4.jar"
hash-format = "murmur2"
hash = "418293098"

[update]
[update.curseforge]
file-id = 3152631
project-id = 430458
release-channel = "beta"
