name = "Supernatural Crops"
filename = "supernatural-crops-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3189/589/supernatural-crops-2.0.2.jar"
hash-format = "murmur2"
hash = "3264337230"

[update]
[update.curseforge]
file-id = 3189589
project-id = 430458
release-channel = "beta"
