name = "Supernatural Crops"
filename = "supernatural-crops-1.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3172/277/supernatural-crops-1.0.6.jar"
hash-format = "murmur2"
hash = "2255848458"

[update]
[update.curseforge]
file-id = 3172277
project-id = 430458
release-channel = "beta"
