name = "Telekinesis Enchantment"
filename = "telekinesis-mod-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3038/663/telekinesis-mod-1.1.0.jar"
hash-format = "murmur2"
hash = "2517618356"

[update]
[update.curseforge]
file-id = 3038663
project-id = 398198
release-channel = "beta"
