name = "TIS-3D"
filename = "TIS-3D-MC1.16.2-Fabric-1.6.1.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3136/22/TIS-3D-MC1.16.2-Fabric-1.6.1.22.jar"
hash-format = "murmur2"
hash = "2435437137"

[update]
[update.curseforge]
file-id = 3136022
project-id = 238603
release-channel = "beta"
