name = "Upstream(Fabric)"
filename = "upstream-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3141/568/upstream-1.0.1.jar"
hash-format = "murmur2"
hash = "1759135199"

[update]
[update.curseforge]
file-id = 3141568
project-id = 428737
release-channel = "beta"
