name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.2.0.2_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3190/740/Xaeros_Minimap_21.2.0.2_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "128274007"

[update]
[update.curseforge]
file-id = 3190740
project-id = 263420
release-channel = "beta"
